[versions]
agp = "8.8.0"
kotlin = "2.1.10"
navigation = "2.8.8"

[libraries]
# ConventionPlugin作るときに使う
gradle_agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle_kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle_navigation = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

[plugins]
agp_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
